### ISSUE TITLE
Broker: add attribute of REST HTTP method in message broker model

### ISSUE THREAD

**Issue by unkcpz** [materials-marketplace/standard-app-api#35]
I use the rpc_server to handle the message and relay to the app. The app is already deployed so there is no need to change basically any code of app server and redeploy it. 
But in order to relay with the right REST HTTP method, (e.g GET, POST ..), I need this information from request_message, which is not attached to the request of message broker at https://github.com/materials-marketplace/standard-app-api/blob/76491d54b26e7cf03ca43f86b8ce1bf2df7ad53b/marketplace_standard_app_api/models/message_broker.py#L6-L10.

**Comment by yoavnash** [comment]
Solved in #36
